# Generated by Django 4.2.1 on 2023-05-11 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_address', models.CharField(max_length=200)),
                ('parmanent_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('user_profile_image', models.ImageField(default='avater.png', upload_to='profileImages', verbose_name='Your profile image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
