# Generated by Django 4.2.1 on 2023-05-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='parmanent_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='present_address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
