# Generated by Django 4.2.1 on 2023-05-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_userregistration_parmanent_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='user_profile_image',
            field=models.ImageField(blank=True, default='avater.png', null=True, upload_to='profileImages', verbose_name='Your profile image'),
        ),
    ]
